### ISSUE TITLE
Loot does not work for larrens key

### ISSUE THREAD

**Issue by Osamu01** [pajlads/DinkPlugin#260] opened 2023-06-18 00:40 UTC
larrens key doesn't work when i set the min+screenshot value to 100k (nothing sends to discord) but if i set it to 0 and kill a man it shows up.

**Comment by Felanbird** [comment] 2023-06-18 00:55
Cannot replicate, did you get loot worth more than 100k?

![image](https://github.com/pajlads/DinkPlugin/assets/41973452/9c65b75f-83e6-424f-a4c0-407be824443a)

**Comment by Osamu01** [comment] 2023-06-18 01:58
> Cannot replicate, did you get loot worth more than 100k?
> 
> ![image](https://user-images.githubusercontent.com/41973452/246638197-9c65b75f-83e6-424f-a4c0-407be824443a.png)

I was referring to larrans key ground loot (the key itself)

**Comment by Felanbird** [comment] 2023-06-18 02:32
Ah my mistake, do Larran's keys properly have their GE value listed on the Runelite `Loot tracker`? 

Our loot notifier just uses the native Runelite tracker and notifies as necessary, so if somehow the value is just sort of missing, it would likely fall back to their HA which is basically nothing.

**Comment by iProdigy** [comment] 2023-06-18 02:46
In your RuneLite settings, do you have wiki prices disabled?

![image](https://github.com/pajlads/DinkPlugin/assets/8106344/02909a81-dccb-4e8a-a689-336a61223266)

**Comment by Osamu01** [comment] 2023-06-18 03:14
> 

yes I do have this 

> Ah my mistake, do Larran's keys properly have their GE value listed on the Runelite `Loot tracker`?
> 
> Our loot notifier just uses the native Runelite tracker and notifies as necessary, so if somehow the value is just sort of missing, it would likely fall back to their HA which is basically nothing.

yes they show as 159k GE price, 378 HA.

**Comment by Osamu01** [comment] 2023-06-18 03:14
> In your RuneLite settings, do you have wiki prices disabled?
> 
> ![image](https://user-images.githubusercontent.com/8106344/242448597-02909a81-dccb-4e8a-a689-336a61223266.png)

yes i do

**Comment by iProdigy** [comment] 2023-06-18 03:21
> yes i do

If yes means you have that checkbox disabled, that would be the cause of the problem.

**Comment by Osamu01** [comment] 2023-06-18 04:08
> > yes i do
> 
> If yes means you have that checkbox disabled, that would be the cause of the problem.

i have it enabled

**Comment by Osamu01** [comment] 2023-06-18 16:27
it didn't work today for ancient emblem either, the 2m one.

**Comment by Felanbird** [comment] 2023-06-18 16:53
> it didn't work today for ancient emblem either, the 2m one.

I have personally seen our loot notifier work for Rev totems in both Feb and April respectively, so unless we managed to accidentally break it, it should work exactly as expected. 
![image](https://github.com/pajlads/DinkPlugin/assets/41973452/89c0c748-1f58-40eb-bf94-e99d9ea89953)

**Comment by Felanbird** [comment] 2023-06-18 17:25
Can you post your `client.log` file for yesterday and today (today's will just be named `client` and yesterday's will be `client_yesterdays-date`)

Steps on how to find that from the Runelite discord:
![image](https://github.com/pajlads/DinkPlugin/assets/41973452/f2aff85b-f792-4fba-84c0-41fc67e41146)

**Comment by Osamu01** [comment] 2023-06-18 18:23
[client_2023-06-17.0.log](https://github.com/pajlads/DinkPlugin/files/11782307/client_2023-06-17.0.log)
[client.log](https://github.com/pajlads/DinkPlugin/files/11782308/client.log)

**Comment by Osamu01** [comment] 2023-06-18 18:52
> Can you post your `client.log` file for yesterday and today (today's will just be named `client` and yesterday's will be `client_yesterdays-date`)
> 
> Steps on how to find that from the Runelite discord: ![image](https://user-images.githubusercontent.com/41973452/246680593-f2aff85b-f792-4fba-84c0-41fc67e41146.png)

I've sent both above

**Comment by Osamu01** [comment] 2023-06-19 14:39
> Confirming our group are currently doing rev/wildy content (pls no pk) and we are getting notifications (latest runelite plugin version), granted they are to a bespoke API, but the embed is also being submitted correctly in our server logs.
> 
> <img alt="Screenshot 2023-06-19 at 9 03 49 PM" width="527" src="https://user-images.githubusercontent.com/13660274/246810971-f564ab3d-a07e-4cbc-a5e3-603393bec7fd.png"> <img alt="Screenshot 2023-06-19 at 9 04 40 PM" width="513" src="https://user-images.githubusercontent.com/13660274/246811162-b25c1efc-9df6-4c57-9101-211a66230461.png">

yeah idk, it's not working for me and i can't figure out why.

**Comment by Felanbird** [comment] 2023-06-19 18:35
> yeah idk, it's not working for me and i can't figure out why.

As of right now our only idea is that the `Collection Log` plugin is having such an issue it's completely breaking all outgoing events. 
It would check out since you have a whole bunch of errors from that plugin in your logs, and since PK'd loot is not collection-log related, it would explain why your PK loot notifications work.

**Comment by Felanbird** [comment] 2023-07-05 04:28
I'm going to go ahead and close this, as I still believe this is a bug with `Collection Log` and not our plugin.

**Closed by Felanbird** 2023-07-05 04:28 UTC
