### ISSUE TITLE
Achivement diary min value is ignored

### ISSUE THREAD

**Issue by redrails** [pajlads/DinkPlugin#381] opened 2023-11-30 14:42 UTC
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

The `Achievement Diary -> Min Difficulty` value is set to "Elite" as I only want to notify on Elite diary completion. However, this setting isn't being respected and instead all Diary tier notifications are being sent. 

I believe the following bit of code is responsible for checking this: https://github.com/pajlads/DinkPlugin/blob/master/src/main/java/dinkplugin/notifiers/DiaryNotifier.java#L208-L210

I don't see anything wrong with the code at first glance, unless the value isn't persisted to the config perhaps?

### Runelite Logs

Nothing substantial in the logs except a massive repetition of the following: 
```
[Client] WARN  dinkplugin.SettingsManager - Pet Notifier cannot reliably identify pet names unless you enable the game setting: Untradeable loot notifications
```

### Runelite Version

1.10.17.1

**Comment by Felanbird** [comment] 2023-11-30 14:58
```
{
   "type":"ACHIEVEMENT_DIARY",
   "playerName":"felanbird1",
   "accountType":"IRONMAN",
   "seasonalWorld":true,
   "extra":{
      "area":"Western Provinces",
      "difficulty":"EASY",
      "total":11,
      "tasksCompleted":197,
      "tasksTotal":492,
      "areaTasksCompleted":24,
      "areaTasksTotal":44
   },
```

difficulty it still correct for the diary in question, it's just ignoring the setting

> Nothing substantial in the logs except a massive repetition of the following:

that's been fixed with https://github.com/pajlads/DinkPlugin/pull/373

**Comment by redrails** [comment] 2023-11-30 15:06
> {
>    "type":"ACHIEVEMENT_DIARY",
>    "playerName":"felanbird1",
>    "accountType":"IRONMAN",
>    "seasonalWorld":true,
>    "extra":{
>       "area":"Western Provinces",
>       "difficulty":"EASY",
>       "total":11,
>       "tasksCompleted":197,
>       "tasksTotal":492,
>       "areaTasksCompleted":24,
>       "areaTasksTotal":44
>    },
> ```

Where is this snippet from?

> difficulty is* still correct for the diary in question, it's just ignoring the setting

Ah okay, I couldn't see any obvious reason why the setting would be ignored as the rest work fine, so I suppose `config.minDiaryDifficulty()` always returns the default value `EASY` currently?

**Comment by redrails** [comment] 2023-11-30 15:25
Right okay, it's a little bit odd when looing at the unit tests the min value is set to `MEDIUM` https://github.com/pajlads/DinkPlugin/blob/master/src/test/java/dinkplugin/notifiers/DiaryNotifierTest.java#L48 and the following test is still valid, but shouldn't be according to what's happening at runtime.

```java
@Test
void testMinDifficultyNotify() {
    // initially many diary completions
    when(client.getVarbitValue(anyInt())).thenReturn(1);
    int total = AchievementDiary.DIARIES.size() - 3;

    // perform enough ticks to trigger diary initialization
    IntStream.range(0, 16).forEach(i -> notifier.onTick());

    // trigger diary started
    int id = Varbits.DIARY_KARAMJA_EASY;
    plugin.onVarbitChanged(event(id, 2));

    // ensure no notification
    verify(messageHandler, never()).createMessage(any(), anyBoolean(), any());
}
```

**Comment by iProdigy** [comment] 2023-11-30 15:27
This is caused by `checkDifficulty` not being called from `onMessageBox` (instead it's only called from `onVarbitChanged`, but either event handler can trigger a notification). Feel free to PR this fix (or I'll do it tonight)

**Closed as completed** 2023-12-01 19:27 UTC
Labels: bug, good first issue, Notifier: Achievement Diary
