### ISSUE TITLE
Medium Desert Diary did not fire notification

### ISSUE THREAD

**Issue by TomBolks** [pajlads/DinkPlugin#124] opened 2023-01-13 19:24 UTC
Maybe related to https://github.com/pajlads/DinkPlugin/issues/93? Got no achievement diary notification in Discord.
![image](https://user-images.githubusercontent.com/17124771/212401681-370b5a52-6057-4ac5-999c-9956f872e33a.png)

**Comment by Felanbird** [comment] 2023-01-13 19:30
Can you check your `client.log`

**Comment by Felanbird** [comment] 2023-01-13 19:36
Likely unrelated but interesting, that there was no `You have completed all of the medium diary tasks, speak to NPC to claim your wards` message in your chat

**Comment by TomBolks** [comment] 2023-01-13 19:37
[client.log](https://github.com/pajlads/DinkPlugin/files/10414856/client.log)
Nothing in the log related to this issue, I think.

**Comment by Felanbird** [comment] 2023-01-13 19:50
Just to help pinpoint the issue to the diary notifier, can you try to trigger any of the other notifiers?

**Comment by TomBolks** [comment] 2023-01-13 19:52
Yeah didn't configure the loot notifier yet so got a worthless drop notification 😛 
![image](https://user-images.githubusercontent.com/17124771/212406892-e2971a66-6d7b-441f-b8bb-bbdc7a14c9a3.png)

**Comment by Felanbird** [comment] 2023-01-16 16:21
I went ahead and completed a diary(lumbridge hard) while having current stable checked out, to see if the entire diary handling was broken and unfortunately the notif fired exactly as expected

As well, pajlada removed the checks preventing notifs from firing during varbit changes on login, and as expected all notifs including Desert Medium fired, so we're still unsure what caused your issue 🌮

**Comment by pajlada** [comment] 2023-01-16 17:04
One way I know of that could make this not fire is if you just enabled the setting right before finishing the step, it takes 8 ticks (~5 seconds) from you enabling the notifier to it being ready to fire things off. If you enabled it and finished the diary before those 5 seconds had finished, it wouldn't be able to fire.

We have two improvements I can see
1) Add better logging for the edge-cases that could cause a diary entry to not fire (specifically log.info or above so they're captured in client.log).
2) Bypassing the 8-tick init delay if the notifier is enabled when the user is already logged in. The delay is there to ensure we don't accidentally fire any diary notifications. We could potentially also fill the `diaryCompletionById` regardless of whether the notifier is active or not, and only reset it on logout/world hop

**Comment by iProdigy** [comment] 2023-01-17 05:21
We're unable to replicate this issue; another user on the stable Dink build had their Medium Desert diary fire as expected today

![image](https://user-images.githubusercontent.com/8106344/212816101-16b04230-9ff4-4e29-8b83-10ece06dae44.png)

&nbsp;

That said, we are reducing the likelihood of a notification skipping due to a recent plugin settings adjustment and adding some logging to help diagnose such edge cases in #129

**Comment by iProdigy** [comment] 2023-01-18 22:54
Duplicate of #93 (given this is a general issue rather than something specific to medium desert)

**Closed by iProdigy** 2023-01-18 22:54 UTC
Labels: bug, Notifier: Achievement Diary
