### ISSUE TITLE
Wrong items reported when depositing Aranea boots

### ISSUE THREAD

**Issue by UsefulEndymion** [pajlads/DinkPlugin#609] opened 2024-11-26 18:53 UTC
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

Group mate got 2 pairs of Aranea boots and deposited them to the group storage, the plugin reported that he withdrew 1 divine rune pouch and 1 pair of karamja gloves 4 (both untradeable so not possible to be in Group storage in the first place).

### Screenshots

![image](https://github.com/user-attachments/assets/34925a6f-6ab5-4131-8051-18d4abb6b059)

### Runelite Logs

[client.log](https://github.com/user-attachments/files/17924540/client.log)

### Runelite Version

1.10.44

**Comment by Felanbird** [comment] 2024-11-26 19:16
Is this a consistent problem or did it happen once? I'm not aware of anything special about this item.

**Comment by iProdigy** [comment] 2024-11-27 06:31
Was the rune pouch configured while the bank interface was opened? Seems like that possibility was introduced back in Feb https://oldschool.runescape.wiki/w/Divine_rune_pouch#Changes

**Comment by iProdigy** [comment] 2024-11-27 06:32
More generally, could you state an exact series of steps to reproduce this issue?

**Comment by iProdigy** [comment] 2024-12-28 05:22
Closing since it's been a month without reproduction - feel free to reopen if you have more context

**Closed by iProdigy** 2024-12-28 05:22 UTC
Labels: question, Notifier: Group Storage, issue-report
